AWSTemplateFormatVersion: '2010-09-09'

# Sets up some parameters in the AWS Systems Manager Parameter store.
# demo 2 will reference them.

Resources:

  ParameterA:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub /${AWS::StackName}/key/a
      Type: String    # Can't do SecureString via CloudFormation
      Value: This is A
      Description: Just an example parameter

  ParameterB:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub /${AWS::StackName}/key/b
      Type: String    # Can't do SecureString via CloudFormation
      Value: This is B
      Description: Just an example parameter

Outputs:
  ParameterAValue:
    Description: The value of parameter A.
    Value: !GetAtt ParameterA.Value 

  ParameterBValue:
    Description: The value of parameter B.
    Value: !GetAtt ParameterB.Value 
