AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://kk-uploads-oregon/index.js
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables: 
          S3_BUCKET: bucket-name

